### ISSUE TITLE
undefined reference to `__stack_chk_guard'

### ISSUE THREAD

**Issue by ibrep** [riscv/riscv-pk#105]
Failed with Linking process.

[...]
riscv64-linux-gnu-gcc -Wl,--build-id=none -nostartfiles -nostdlib -static   -o pk pk.o -L.  -lpk  -lmachine  -lsoftfloat  -lutil -lgcc -T ../pk/pk.lds
pk.o: In function `rest_of_boot_loader':
pk.c:(.text+0x0): undefined reference to `__stack_chk_guard'
./libpk.a(file.o): In function `file_pwrite':
file.c:(.text+0x39c): undefined reference to `__stack_chk_guard'
./libpk.a(file.o): In function `.L0 ':
file.c:(.text+0x406): undefined reference to `__stack_chk_fail'
./libpk.a(elf.o): In function `load_elf':
elf.c:(.text+0x0): undefined reference to `__stack_chk_guard'
elf.c:(.text+0x1e8): undefined reference to `__stack_chk_guard'
elf.c:(.text+0x216): undefined reference to `__stack_chk_fail'
./libpk.a(console.o): In function `.L0 ':
console.c:(.text+0x4): undefined reference to `__stack_chk_guard'
console.c:(.text+0x50): undefined reference to `__stack_chk_fail'
./libpk.a(console.o): In function `.L7':
console.c:(.text+0x5c): undefined reference to `__stack_chk_guard'
./libpk.a(console.o): In function `.L0 ':
console.c:(.text+0x96): undefined reference to `__stack_chk_fail'
./libpk.a(console.o): In function `.L22':
console.c:(.text+0x150): undefined reference to `__stack_chk_guard'
./libpk.a(syscall.o): In function `sys_chdir':
syscall.c:(.text+0x750): undefined reference to `__stack_chk_guard'
./libpk.a(syscall.o): In function `sys_ftruncate':
syscall.c:(.text+0x7da): undefined reference to `__stack_chk_fail'
syscall.c:(.text+0x7e6): undefined reference to `__stack_chk_guard'
./libpk.a(syscall.o): In function `.L168':
syscall.c:(.text+0x898): undefined reference to `__stack_chk_fail'
./libmachine.a(mtrap.o): In function `.L47':
mtrap.c:(.text+0x16c): undefined reference to `__stack_chk_guard'
./libmachine.a(mtrap.o): In function `.L0 ':
mtrap.c:(.text+0x18e): undefined reference to `__vsnprintf_chk'
./libmachine.a(mtrap.o): In function `.L55':
mtrap.c:(.text+0x1bc): undefined reference to `__stack_chk_fail'
./libmachine.a(mtrap.o): In function `.L53':
mtrap.c:(.text+0x1c8): undefined reference to `__stack_chk_guard'
./libmachine.a(mtrap.o): In function `.L0 ':
mtrap.c:(.text+0x202): undefined reference to `__stack_chk_fail'
./libmachine.a(htif.o): In function `.L0 ':
htif.c:(.text+0x262): undefined reference to `__stack_chk_guard'
htif.c:(.text+0x2aa): undefined reference to `__stack_chk_fail'
./libmachine.a(uart.o): In function `uart_getchar':
uart.c:(.text+0xde): undefined reference to `__stack_chk_guard'
./libmachine.a(uart.o): In function `.L0 ':
uart.c:(.text+0x124): undefined reference to `__stack_chk_fail'
./libmachine.a(uart16550.o): In function `uart16550_getchar':
uart16550.c:(.text+0x106): undefined reference to `__stack_chk_guard'
./libmachine.a(uart16550.o): In function `.L0 ':
uart16550.c:(.text+0x14c): undefined reference to `__stack_chk_fail'
./libmachine.a(finisher.o): In function `finisher_exit':
finisher.c:(.text+0xce): undefined reference to `__stack_chk_guard'
./libmachine.a(finisher.o): In function `.L0 ':
finisher.c:(.text+0x114): undefined reference to `__stack_chk_fail'
./libmachine.a(fdt.o): In function `.L144':
fdt.c:(.text+0x93e): undefined reference to `__stack_chk_guard'
./libmachine.a(fdt.o): In function `.L162':
fdt.c:(.text+0xbb2): undefined reference to `__stack_chk_fail'
./libmachine.a(fdt.o): In function `.L0 ':
fdt.c:(.text+0x124e): undefined reference to `__stack_chk_guard'
fdt.c:(.text+0x12d2): undefined reference to `__stack_chk_fail'
fdt.c:(.text+0x12de): undefined reference to `__stack_chk_guard'
fdt.c:(.text+0x1370): undefined reference to `__stack_chk_fail'
fdt.c:(.text+0x137c): undefined reference to `__stack_chk_guard'
./libmachine.a(fdt.o): In function `.L292':
fdt.c:(.text+0x13f0): undefined reference to `__stack_chk_fail'
./libmachine.a(fdt.o): In function `.L0 ':
fdt.c:(.text+0x13fc): undefined reference to `__stack_chk_guard'
fdt.c:(.text+0x1446): undefined reference to `__stack_chk_fail'
fdt.c:(.text+0x1452): undefined reference to `__stack_chk_guard'
./libmachine.a(fdt.o): In function `query_clint':
fdt.c:(.text+0x149c): undefined reference to `__stack_chk_fail'
fdt.c:(.text+0x14a8): undefined reference to `__stack_chk_guard'
fdt.c:(.text+0x14f8): undefined reference to `__stack_chk_fail'
fdt.c:(.text+0x1504): undefined reference to `__stack_chk_guard'
./libmachine.a(fdt.o): In function `.L0 ':
fdt.c:(.text+0x1552): undefined reference to `__stack_chk_fail'
./libmachine.a(misaligned_ldst.o): In function `misaligned_load_trap':
misaligned_ldst.c:(.text+0x0): undefined reference to `__stack_chk_guard'
misaligned_ldst.c:(.text+0x1fa): undefined reference to `__stack_chk_fail'
misaligned_ldst.c:(.text+0x202): undefined reference to `__stack_chk_guard'
./libmachine.a(misaligned_ldst.o): In function `.L18':
misaligned_ldst.c:(.text+0x3f2): undefined reference to `__stack_chk_fail'
./libsoftfloat.a(f32_to_f64.o): In function `.L0 ':
f32_to_f64.c:(.text+0x4): undefined reference to `__stack_chk_guard'
./libsoftfloat.a(f32_to_f64.o): In function `.L15':
f32_to_f64.c:(.text+0xa0): undefined reference to `__stack_chk_fail'
./libsoftfloat.a(f64_to_f32.o): In function `.L0 ':
f64_to_f32.c:(.text+0x4): undefined reference to `__stack_chk_guard'
./libsoftfloat.a(f64_to_f32.o): In function `.L5':
f64_to_f32.c:(.text+0xb0): undefined reference to `__stack_chk_fail'
./libutil.a(snprintf.o): In function `.L0 ':
snprintf.c:(.text+0x274): undefined reference to `__stack_chk_guard'
snprintf.c:(.text+0x2aa): undefined reference to `__stack_chk_fail'
collect2: error: ld returned 1 exit status
Makefile:302: recipe for target 'pk' failed
make: *** [pk] Error 1

**Comment by ibrep** [comment]
Add -fno-stack-protector to CFLAGS and LDFLAGS in Makefile.in, now it complaints:
[...]
riscv64-linux-gnu-ar rcv libutil.a snprintf.o string.o
a - snprintf.o
a - string.o
riscv64-linux-gnu-ranlib libutil.a
riscv64-linux-gnu-gcc -MMD -MP -Wall -Werror -D__NO_INLINE__ -mcmodel=medany -O2 -std=gnu99 -Wno-unused -Wno-attributes -fno-delete-null-pointer-checks -fno-PIE  -DBBL_PAYLOAD=\"bbl_payload\" -DBBL_LOGO_FILE=\"bbl_logo_file\" -fno-stack-protector -I. -I../pk -I../bbl -I../softfloat -I../dummy_payload -I../machine -I../util -c ../pk/pk.c
riscv64-linux-gnu-gcc -Wl,--build-id=none -nostartfiles -nostdlib -static  -fno-stack-protector -o pk pk.o -L.  -lpk  -lmachine  -lsoftfloat  -lutil -lgcc -T ../pk/pk.lds
./libmachine.a(mtrap.o): In function `vprintm':
mtrap.c:(.text+0x17e): undefined reference to `__vsnprintf_chk'
collect2: error: ld returned 1 exit status
Makefile:302: recipe for target 'pk' failed
make: *** [pk] Error 1

**Comment by anmolsahoo25** [comment]
Adding the following linker flag, -U_FORTIFY_SOURCE fixes the error for me. But you have to wait for one of the devs to get back and explain the implications of these flags, as right now I do not have a clear picture of what these flags do.

**Comment by aswaterman** [comment]
This project is meant to be built with a bare-metal toolchain, not a toolchain that builds user-level applications. I’m sure you can make it work, given the right set of compiler flags, but supporting that configuration is out of scope.
