### ISSUE TITLE
sbi_num_harts not getting the correct number of CPUs on FPGA

### ISSUE THREAD

**Issue by zhemao** [riscv/riscv-pk#11]
When booting Linux on a dual-core rocket instance on the FPGA, sbi_num_harts still returns 1. How is the num_harts variable set? From what I can tell, it seems to be parsing the command line to get the number.

**Comment by aswaterman** [comment]
If I had to guess, it's a bug in the host software side of the HTIF.
 sbi_num_harts on the target should ultimately return the same thing as
does htif_t::num_cores.

**Comment by sbeamer** [comment]
This was fixed with https://github.com/riscv/riscv-fesvr/commit/5fc6b74b2b1fb3232093f9e7299f23e042bc81c3.
