### ISSUE TITLE
How does one build a standalone bbl?

### ISSUE THREAD

**Issue by marcopeereboom** [riscv/riscv-pk#155]
I read through the doco and searched the web but I could not find the magic to build a bbl that can be used to boot qemu with vmlinux instead of linking the bbl+kernel together.

Any clues?

**Comment by davidlt** [comment]
IIRC upstream QEMU doesn't support separate BBL (firmware) and vmlinuz (kernel) files, but patches were posted in 2018 May, I think.

I would advice you to use OpenSBI instead ( https://github.com/riscv/opensbi ) which also has jump variant. Then modify QEMU line accordingly:
```
	-kernel build/platform/qemu/virt/firmware/fw_jump.elf \
	-device loader,file=<linux_build_directory>/arch/riscv/boot/Image,addr=0x80400000
```

There are more documentation and examples on OpenSBI GitHub page.

**Comment by marcopeereboom** [comment]
Thank you.

**Comment by marcopeereboom** [comment]
Yep this works like a charm. It would be helpful to send people to OpenSBI and deprecate this repo.
