### ISSUE TITLE
Building bbl fails attempting to compile non-existent DTS file

### ISSUE THREAD

**Issue by repnop** [riscv/riscv-pk#218]
Looks like a161e6f3ef31004e47a5b94b85c2e84b764f8637 broke the build process. I don't provide any DTS files for it to use and spent the last while trying to understand why the build broke (I did some reorganization in a project that uses bbl and had the build silenced at first), it spits out
```
dtc -O dtb  -o machine.dtb
Error: <stdin>:0.0 syntax error
FATAL ERROR: Unable to parse input tree
make: *** [machine.mk:44: machine.dtb] Error 1
```
which stems from
https://github.com/riscv/riscv-pk/blob/a161e6f3ef31004e47a5b94b85c2e84b764f8637/machine/machine.mk.in#L43-L44
rolling back to the parent commit works

**Comment by aswaterman** [comment]
Ugh.  Thanks.

**Comment by repnop** [comment]
Wow that was quick! Thank you! :)
