### ISSUE TITLE
malloc calls memset

### ISSUE THREAD

**Issue by zinechant** [riscv/riscv-pk#238]
This would pollute caches and produce strange cache numbers in spike-isa-sim. Especially for the case where compute is not intensive, or for the case when a large array is malloced but only a small portion is used.
Opening this issue to open the discussion on whether this memset is necessary.

**Comment by aswaterman** [comment]
It is necessary.  mmap'ed pages are required to be zeroed, and of course there's no guarantee that main memory is already zeroed.  (The fact that Spike zeroes main memory at boot is an implementation detail and is not true of other RISC-V implementations.)

Besides mmap, other uses of __page_alloc within pk rely on the zero initialization, including when new page tables are allocated.

**Comment by aswaterman** [comment]
Search for the word "zero-fills" on this page for more details on the mmap situation: https://pubs.opengroup.org/onlinepubs/7908799/xsh/mmap.html

**Comment by zinechant** [comment]
That was fast! Thanks!
I am happy with a little hack that commenting out the memset for my purpose.
Going to close this issue.

**Comment by aswaterman** [comment]
Cool, good luck.
