### ISSUE TITLE
Error during make

### ISSUE THREAD

**Issue by Marytv** [riscv/riscv-pk#249]
I need to build a 32 bit version of pk and bbl and did following steps.

$ mkdir build
$ cd build
$../configure --prefix=$RISCV --host=riscv32-unknown-elf --with-arch=rv32i
$make

make give me the following error. How to solve this?

../machine/mtrap.h:51:29: error: initialization of 'uintptr_t *' {aka 'unsigned int *'} from incompatible pointer type 'char *' [-Werror=incompatible-pointer-types]
   51 | #define MACHINE_STACK_TOP() ({ \
      |                             ^
../machine/minit.c:246:23: note: in expansion of macro 'MACHINE_STACK_TOP'
  246 |   uintptr_t *p_fcsr = MACHINE_STACK_TOP() - MENTRY_FRAME_SIZE; // the x0's save slot
      |                       ^~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make: *** [Makefile:336: minit.o] Error 1

**Comment by aswaterman** [comment]
Sorry about that; recent attempts to remove undefined behavior in the code have injected a handful of new problems.  I'll push a fix.
