### ISSUE TITLE
spike pk hello. could not open pk

### ISSUE THREAD

**Issue by ninode** [riscv/riscv-pk#52]
Hello,

 I know this has been asked so many times and I still can't solve it following other responses.
I cloned my sources from the **rocket-chip** git.

The toolchain built was successful (adding zlib).

 When I run **spike pk hello** it yields: 
```
terminate called after throwing an instance of 'std::runtime_error'
  what():  could not open pk

```

So, I need guidance and instructions for setting up the environment variables (I'm new to linux). Also, I've noticed that building from the LowRISC repo worked for me as opposed to building from the _rocket-chip_ repo. in _LowRISC_ **spike pk hello** works fine after I source the _set_riscv_env file._ In _rocket-chip_ there isn't such file, and I don't know how I can set up the environment myself. 

Also, when I configured the _riscv-pk/build_ directory I ran **../configure --prefix=$RISCV/ --host=riscv64-unknown-elf**. Then  **../configure --prefix=$RISCV/riscv64-unknown-elf/bin/pk --host=riscv64-unknown-elf**. Both didn't work.

Does anyone know how I can fix this ? 

Thank you :)

**Comment by adamsir32** [comment]
hello，i have the same qustion，how to solve it？thank you

**Comment by jundijiujieke** [comment]
Did you fix this problem, I already install the pk on my linux, but they can't find it. Please tell me how to fix this problem.
