### ISSUE TITLE
Double-Checked Lock in __vmr_alloc in mmap.c

### ISSUE THREAD

**Issue by markww** [riscv/riscv-pk#64]
I was looking in mmap.c and noticed the following code:

```C

static vmr_t* vmrs;

static uintptr_t __page_alloc()
{
  kassert(next_free_page != free_pages);
  uintptr_t addr = first_free_page + RISCV_PGSIZE * next_free_page++;
  memset((void*)addr, 0, RISCV_PGSIZE);
  return addr;
}

static vmr_t* __vmr_alloc(uintptr_t addr, size_t length, file_t* file,
                          size_t offset, unsigned refcnt, int prot)
{
  if (!vmrs) {
    spinlock_lock(&vm_lock);
      if (!vmrs)
        vmrs = (vmr_t*)__page_alloc();
    spinlock_unlock(&vm_lock);
  }
 /* ... */
```

The above is a straightforward example of the common double-checked-lock anti-pattern. In essence, the outer unlocked check of vmrs is used to check to see whether vmrs has been initialized. Unfortunately, vmrs not being NULL is no guarantee it has been fully initialized; if __page_alloc is inlined into __vmr_alloc, it is possible that it assigns vmrs a non-null value before the memset of the pointed-to memory completes. This can cause problems later if vmrs is used by another thread before fully initialized; for instance, if the other thread notes that vmrs is not null before the memset completes, it may be fooled into believing that a garbage value for an element's refct is genuine.

This can be fixed by simply deleting the check of vmrs outside of the lock.

**Comment by aswaterman** [comment]
The problem is just that there's no ordering between the call to __page_alloc and the assignment to vmrs.  I'll add a memory barrier.

**Comment by aswaterman** [comment]
4c64de3213e7a08e4097970b26a14ad835cabfab
