### ISSUE TITLE
build fails on arch linux

### ISSUE THREAD

**Issue by rain-1** [riscv/riscv-pk#78]
Hello, I am on x86_64 GNU/Linux arch linux.

I did`../configure --host=riscv64-unknown-elf` but

```
$ make
gcc -MMD -MP -Wall -Werror -D__NO_INLINE__ -mcmodel=medany -O2 -std=gnu99 -Wno-unused -Wno-attributes -fno-delete-null-pointer-checks  -DBBL_PAYLOAD=\"bbl_payload\" -DBBL_LOGO_FILE=\"bbl_logo_file\" -I. -I../pk -I../bbl -I../softfloat -I../dummy_payload -I../machine -I../util -c ../pk/file.c
gcc: error: unrecognized argument in option ‘-mcmodel=medany’
gcc: note: valid arguments to ‘-mcmodel=’ are: 32 kernel large medium small; did you mean ‘medium’?
make: *** [Makefile:302: file.o] Error 1
```

If I try the gcc command with `-mcmodel=medany` deleted it give this error:

```
../pk/file.c: Assembler messages:
../pk/file.c:28: Error: no such instruction: `fence'
```

**Comment by sorear** [comment]
You seem to be trying to build pk/bbl with an x86_64 compiler.  Was riscv64-unknown-elf-gcc in PATH at the time of the configure?

**Comment by rain-1** [comment]
ah I understand, I didn't realize I needed a riscv toolchain to build this. Thank you.

**Comment by Crosshairs** [comment]
> You seem to be trying to build pk/bbl with an x86_64 compiler. Was riscv64-unknown-elf-gcc in PATH at the time of the configure?

But  riscv64-unknown-elf-gcc in PATH at the time of the configure.Why still have the error:unrecognized argument in option ‘-mcmodel=medany’
