### ISSUE TITLE
#error single-float only is not supported

### ISSUE THREAD

**Issue by Tong-Lin** [riscv/riscv-pk#81]
I got this error while build pk using riscv32-unkonwn-elf  with config --with-arch=rv32imafc ?
"
>Removing existing riscv-pk/build directory
>Configuring project riscv-pk
>Building project riscv-pk
>../machine/fp_asm.S:6:3: error: #error single-float only is not supported
> # error single-float only is not supported
>   ^~~~~
>make: *** [fp_asm.o] Error 1
>make: *** Waiting for unfinished jobs....
"

**Comment by sorear** [comment]
that means that pk does not support imafc, use imafdc or imac instead.
