### ISSUE TITLE
riscv-pk is broken if GCC adds build-id notes

### ISSUE THREAD

**Issue by rwmjones** [riscv/riscv-pk#88]
The Fedora GCC is configured to add build-id notes.  Unfortunately the riscv-pk linker script puts the build-id section at address 0x8000_0000 which breaks booting.

There are various ways to fix this.  A simple way is to modify the bbl linker script so that it puts the build-id note into the bss.  This patch was by Stef O'Rear:

```
diff --git a/bbl/bbl.lds b/bbl/bbl.lds
index 2fd0d7c..59aeed1 100644
--- a/bbl/bbl.lds
+++ b/bbl/bbl.lds
@@ -94,6 +94,7 @@ SECTIONS
     *(.bss.*)
     *(.sbss*)
     *(.gnu.linkonce.b.*)
+    *(.note.gnu.build-id)
     *(COMMON)
   }
```

But there are other ways too.  You could add `-Wl,--build-id=none` to the linker command.  Or there is likely to be some way to suppress build-ids in the linker script.

**Comment by aswaterman** [comment]
Putting it in bss gives me ```section `.bss' type changed to PROGBITS```.  I'll just add ```-Wl,--build-id=none``` to the command line.  Thanks.
